package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/nawodyaishan/universal-mcp-sync/pkg/uxexplore"
)

func main() {
	var (
		outDir        string
		exclusions    string
		allowlist     string
		dashboardSrc  string
		emitAllowlist bool
		expiresInDays int
	)
	flag.StringVar(&outDir, "out", filepath.Join("artifacts", "ux-explore"), "output directory for findings + coverage + graph artifacts")
	flag.StringVar(&exclusions, "exclusions", filepath.Join("pkg", "uxexplore", "exclusions.yaml"), "path to exclusions.yaml")
	flag.StringVar(&allowlist, "allowlist", filepath.Join("pkg", "uxexplore", "findings-allowlist.yaml"), "path to findings-allowlist.yaml")
	flag.StringVar(&dashboardSrc, "dashboard-src", filepath.Join("pkg", "tui", "dashboard.go"), "path to dashboard.go for keymap audit")
	flag.BoolVar(&emitAllowlist, "emit-allowlist", false, "write current findings as allowlist entries to stdout and exit 0")
	flag.IntVar(&expiresInDays, "allowlist-expires-in", 60, "expiry window (days) used by --emit-allowlist")
	flag.Parse()

	if err := run(outDir, exclusions, allowlist, dashboardSrc, emitAllowlist, expiresInDays); err != nil {
		fmt.Fprintln(os.Stderr, "ux-explore:", err)
		os.Exit(1)
	}
}

func run(outDir, exclusionsPath, allowlistPath, dashboardSrc string, emitAllowlist bool, expiresInDays int) error {
	exclusions, err := uxexplore.LoadExclusions(exclusionsPath)
	if err != nil {
		return fmt.Errorf("load exclusions: %w", err)
	}
	allowed, err := uxexplore.LoadAllowlist(allowlistPath)
	if err != nil {
		return fmt.Errorf("load allowlist: %w", err)
	}

	fixtures := uxexplore.EnumerateFixtures()
	traces := make([]*uxexplore.Trace, 0, len(fixtures))
	for _, fixture := range fixtures {
		d, err := uxexplore.NewDriver(fixture)
		if err != nil {
			return fmt.Errorf("driver %s: %w", fixture.Name, err)
		}
		trace, err := d.Explore(context.Background())
		if err != nil {
			return fmt.Errorf("explore %s: %w", fixture.Name, err)
		}
		traces = append(traces, trace)
	}

	findings := uxexplore.Analyze(traces)

	handlers, err := uxexplore.ParseHandlerKeys(dashboardSrc)
	if err != nil {
		return fmt.Errorf("parse handler keys: %w", err)
	}
	findings = append(findings, uxexplore.AuditKeymap(handlers, traces)...)

	if emitAllowlist {
		expiry := time.Now().AddDate(0, 0, expiresInDays).Format("2006-01-02")
		fmt.Println("# Generated by `ux-explore --emit-allowlist`.")
		fmt.Println("# Each entry expires automatically; remove or shorten as findings are addressed.")
		fmt.Println("allowlist:")
		for _, f := range findings {
			fmt.Printf("  - matrix_id: %s\n", f.MatrixID)
			fmt.Printf("    reason: %q\n", fmt.Sprintf("baseline %s on %s/%s", f.Kind, f.State.Screen, f.State.PreconditionClass))
			fmt.Printf("    expires_at: %s\n", expiry)
		}
		return nil
	}

	coverage := uxexplore.ComputeCoverage(traces, exclusions)

	if err := uxexplore.WriteFindings(outDir, findings, coverage, traces); err != nil {
		return fmt.Errorf("write findings: %w", err)
	}

	remaining, expired := uxexplore.FilterFindings(findings, allowed, time.Now())
	gaps := coverage.Gaps()

	fmt.Printf("ux-explore: %d findings (%d allowlisted, %d remaining)\n", len(findings), len(findings)-len(remaining), len(remaining))
	fmt.Printf("ux-explore: coverage gaps: %d\n", len(gaps))
	fmt.Printf("ux-explore: artifacts written to %s\n", outDir)

	fail := false
	if len(remaining) > 0 {
		fmt.Fprintln(os.Stderr, "ux-explore: unallowlisted findings present:")
		for _, f := range remaining {
			fmt.Fprintf(os.Stderr, "  %s %s on %s/%s — %s\n", f.MatrixID, f.Kind, f.State.Screen, f.State.PreconditionClass, f.Recommendation)
		}
		fail = true
	}
	if len(gaps) > 0 {
		fmt.Fprintln(os.Stderr, "ux-explore: coverage gaps (precondition classes never reached):")
		for _, g := range gaps {
			fmt.Fprintf(os.Stderr, "  %s\n", g)
		}
		fail = true
	}
	if len(expired) > 0 {
		fmt.Fprintln(os.Stderr, "ux-explore: expired allowlist entries:")
		for _, e := range expired {
			fmt.Fprintf(os.Stderr, "  %s expired %s — %s\n", e.MatrixID, e.ExpiresAt.Format("2006-01-02"), e.Reason)
		}
		fail = true
	}
	if fail {
		return fmt.Errorf("ux-explore gate failed")
	}
	return nil
}
