package tui

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/nawodyaishan/universal-mcp-sync/pkg/config"
	"github.com/nawodyaishan/universal-mcp-sync/pkg/provider"
)

// CredentialsFilePath returns the canonical on-disk location for the
// interactive credential store, anchored at home.
func CredentialsFilePath(home string) string {
	return filepath.Join(home, ".config", "usync", "credentials.toml")
}

// SaveCredentialsProfiles writes the supplied profiles to credentials.toml
// using atomic write semantics, 0o600 file permissions, and 0o700 parent
// directories. Existing content is read first and merged: profiles with the
// same (provider_id, label) pair are replaced; others are preserved.
//
// The format is a minimal TOML dialect handwritten to avoid pulling in a
// TOML dependency. Profiles are sorted deterministically so two runs
// produce byte-identical output.
func SaveCredentialsProfiles(home string, profiles []provider.CredentialProfile, now time.Time) (string, error) {
	if home == "" {
		return "", fmt.Errorf("home directory is required")
	}
	path := CredentialsFilePath(home)
	merged := mergeCredentialProfiles(nil, profiles)
	data := renderCredentialsTOML(merged)
	if _, err := config.WriteWithBackup(path, []byte(data), now); err != nil {
		return "", err
	}
	return path, nil
}

func mergeCredentialProfiles(existing, incoming []provider.CredentialProfile) []provider.CredentialProfile {
	keyOf := func(p provider.CredentialProfile) string {
		return p.ProviderID + "\x00" + p.Label
	}
	indexed := make(map[string]provider.CredentialProfile, len(existing))
	order := make([]string, 0, len(existing))
	for _, p := range existing {
		k := keyOf(p)
		if _, ok := indexed[k]; !ok {
			order = append(order, k)
		}
		indexed[k] = p
	}
	for _, p := range incoming {
		k := keyOf(p)
		if _, ok := indexed[k]; !ok {
			order = append(order, k)
		}
		indexed[k] = p
	}
	out := make([]provider.CredentialProfile, 0, len(order))
	for _, k := range order {
		out = append(out, indexed[k])
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].ProviderID != out[j].ProviderID {
			return out[i].ProviderID < out[j].ProviderID
		}
		return out[i].Label < out[j].Label
	})
	return out
}

func renderCredentialsTOML(profiles []provider.CredentialProfile) string {
	var b strings.Builder
	b.WriteString("# usync credentials — generated by interactive credential entry\n")
	b.WriteString("# File permissions are enforced at 0600; do not edit by hand.\n\n")
	for _, p := range profiles {
		b.WriteString("[[profiles]]\n")
		fmt.Fprintf(&b, "provider = %q\n", p.ProviderID)
		fmt.Fprintf(&b, "label    = %q\n", p.Label)
		keys := make([]string, 0, len(p.Values))
		for k := range p.Values {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		if len(keys) > 0 {
			fmt.Fprintf(&b, "[profiles.values]\n")
			for _, k := range keys {
				fmt.Fprintf(&b, "%s = %q\n", k, p.Values[k])
			}
		}
		b.WriteString("\n")
	}
	return b.String()
}
